//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IoTMM.App.Strings {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IoTMM.App.Strings.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location is required to fulfill the assessment..
        /// </summary>
        internal static string AndroidLocationPermissions {
            get {
                return ResourceManager.GetString("AndroidLocationPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read phone state is required. We need to access your device info for security setup..
        /// </summary>
        internal static string AndroidPhonePermissions {
            get {
                return ResourceManager.GetString("AndroidPhonePermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IoT Maturity Diagnostic App.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEED HELP?.
        /// </summary>
        internal static string AssessmentNeedHelp {
            get {
                return ResourceManager.GetString("AssessmentNeedHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business.
        /// </summary>
        internal static string AssessmentResultBusinessTitle {
            get {
                return ResourceManager.GetString("AssessmentResultBusinessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People.
        /// </summary>
        internal static string AssessmentResultPeopleTitle {
            get {
                return ResourceManager.GetString("AssessmentResultPeopleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technology.
        /// </summary>
        internal static string AssessmentResultTechnologyTitle {
            get {
                return ResourceManager.GetString("AssessmentResultTechnologyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        internal static string AssessmentResultTitle {
            get {
                return ResourceManager.GetString("AssessmentResultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assessment.
        /// </summary>
        internal static string AssessmentTitle {
            get {
                return ResourceManager.GetString("AssessmentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEVICES.
        /// </summary>
        internal static string ButtonDevices {
            get {
                return ResourceManager.GetString("ButtonDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFFERS.
        /// </summary>
        internal static string ButtonOffers {
            get {
                return ResourceManager.GetString("ButtonOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PARTNERS.
        /// </summary>
        internal static string ButtonPartners {
            get {
                return ResourceManager.GetString("ButtonPartners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRAININGS.
        /// </summary>
        internal static string ButtonTrainings {
            get {
                return ResourceManager.GetString("ButtonTrainings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m a customer.
        /// </summary>
        internal static string CustomerButtonText {
            get {
                return ResourceManager.GetString("CustomerButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AREA*.
        /// </summary>
        internal static string CustomerProfileArea {
            get {
                return ResourceManager.GetString("CustomerProfileArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pick an area.
        /// </summary>
        internal static string CustomerProfileAreaLowercase {
            get {
                return ResourceManager.GetString("CustomerProfileAreaLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPANY NAME*.
        /// </summary>
        internal static string CustomerProfileCompanyName {
            get {
                return ResourceManager.GetString("CustomerProfileCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to company name.
        /// </summary>
        internal static string CustomerProfileCompanyNameLowercase {
            get {
                return ResourceManager.GetString("CustomerProfileCompanyNameLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIGITAL TRANSFORMATION STRATEGY.
        /// </summary>
        internal static string CustomerProfileDigitalTransformation {
            get {
                return ResourceManager.GetString("CustomerProfileDigitalTransformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to digital transformation strategy.
        /// </summary>
        internal static string CustomerProfileDigitalTransformationLowercase {
            get {
                return ResourceManager.GetString("CustomerProfileDigitalTransformationLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIVISION.
        /// </summary>
        internal static string CustomerProfileDivision {
            get {
                return ResourceManager.GetString("CustomerProfileDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to division.
        /// </summary>
        internal static string CustomerProfileDivisionLowercase {
            get {
                return ResourceManager.GetString("CustomerProfileDivisionLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMAIL.
        /// </summary>
        internal static string CustomerProfileEmail {
            get {
                return ResourceManager.GetString("CustomerProfileEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customer email.
        /// </summary>
        internal static string CustomerProfileEmailLowercase {
            get {
                return ResourceManager.GetString("CustomerProfileEmailLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HAS PREMIER CONTACT?.
        /// </summary>
        internal static string CustomerProfileHasPremierContact {
            get {
                return ResourceManager.GetString("CustomerProfileHasPremierContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to premier contact name.
        /// </summary>
        internal static string CustomerProfileHasPremierContactLowercase {
            get {
                return ResourceManager.GetString("CustomerProfileHasPremierContactLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOT TOPICS.
        /// </summary>
        internal static string CustomerProfileHotTopics {
            get {
                return ResourceManager.GetString("CustomerProfileHotTopics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hot topics or competitive issues/concerns.
        /// </summary>
        internal static string CustomerProfileHotTopicsLowercase {
            get {
                return ResourceManager.GetString("CustomerProfileHotTopicsLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COUNTRY.
        /// </summary>
        internal static string CustomerProfileHQ {
            get {
                return ResourceManager.GetString("CustomerProfileHQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company HQ country.
        /// </summary>
        internal static string CustomerProfileHQLowercase {
            get {
                return ResourceManager.GetString("CustomerProfileHQLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INDUSTRY*.
        /// </summary>
        internal static string CustomerProfileIndustry {
            get {
                return ResourceManager.GetString("CustomerProfileIndustry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customer industry.
        /// </summary>
        internal static string CustomerProfileIndustryLowercase {
            get {
                return ResourceManager.GetString("CustomerProfileIndustryLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDENTIFIED IOT BUSINESS CAPABILITIES.
        /// </summary>
        internal static string CustomerProfileIoT {
            get {
                return ResourceManager.GetString("CustomerProfileIoT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MICROSOFT ASSESSMENT LEAD.
        /// </summary>
        internal static string CustomerProfileLead {
            get {
                return ResourceManager.GetString("CustomerProfileLead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lead name.
        /// </summary>
        internal static string CustomerProfileLeadLowercase {
            get {
                return ResourceManager.GetString("CustomerProfileLeadLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAME*.
        /// </summary>
        internal static string CustomerProfileName {
            get {
                return ResourceManager.GetString("CustomerProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        internal static string CustomerProfileNameLowercase {
            get {
                return ResourceManager.GetString("CustomerProfileNameLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TITLE.
        /// </summary>
        internal static string CustomerProfilePersonTitle {
            get {
                return ResourceManager.GetString("CustomerProfilePersonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to title.
        /// </summary>
        internal static string CustomerProfilePersonTitleLowercase {
            get {
                return ResourceManager.GetString("CustomerProfilePersonTitleLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHONE.
        /// </summary>
        internal static string CustomerProfilePhone {
            get {
                return ResourceManager.GetString("CustomerProfilePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customer phone.
        /// </summary>
        internal static string CustomerProfilePhoneLowercase {
            get {
                return ResourceManager.GetString("CustomerProfilePhoneLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START.
        /// </summary>
        internal static string CustomerProfileStartAssessment {
            get {
                return ResourceManager.GetString("CustomerProfileStartAssessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some required fields are missing.
        /// </summary>
        internal static string CustomerProfileStartAssessmentError {
            get {
                return ResourceManager.GetString("CustomerProfileStartAssessmentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIMEZONE*.
        /// </summary>
        internal static string CustomerProfileTimezone {
            get {
                return ResourceManager.GetString("CustomerProfileTimezone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pick a timezone.
        /// </summary>
        internal static string CustomerProfileTimezoneLowercase {
            get {
                return ResourceManager.GetString("CustomerProfileTimezoneLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer profile.
        /// </summary>
        internal static string CustomerProfileTitle {
            get {
                return ResourceManager.GetString("CustomerProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has ocurred and the call could not be completed. Try again..
        /// </summary>
        internal static string InternetCallErrorDesc {
            get {
                return ResourceManager.GetString("InternetCallErrorDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has ocurred.
        /// </summary>
        internal static string InternetCallErrorTitle {
            get {
                return ResourceManager.GetString("InternetCallErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASSWORD.
        /// </summary>
        internal static string LoginPassword {
            get {
                return ResourceManager.GetString("LoginPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START.
        /// </summary>
        internal static string LoginStartButton {
            get {
                return ResourceManager.GetString("LoginStartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login failed.
        /// </summary>
        internal static string LoginStartButtonError {
            get {
                return ResourceManager.GetString("LoginStartButtonError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMAIL.
        /// </summary>
        internal static string LoginUsername {
            get {
                return ResourceManager.GetString("LoginUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m a Microsoft employee.
        /// </summary>
        internal static string MicrosoftButtonText {
            get {
                return ResourceManager.GetString("MicrosoftButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft employee.
        /// </summary>
        internal static string MicrosoftEmployeeTitle {
            get {
                return ResourceManager.GetString("MicrosoftEmployeeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet connection not available at this moment, try again later..
        /// </summary>
        internal static string NoInternetDesc {
            get {
                return ResourceManager.GetString("NoInternetDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No internet.
        /// </summary>
        internal static string NoInternetTitle {
            get {
                return ResourceManager.GetString("NoInternetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ok.
        /// </summary>
        internal static string OkLowerCase {
            get {
                return ResourceManager.GetString("OkLowerCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OkUpperCase {
            get {
                return ResourceManager.GetString("OkUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t get setting value.
        /// </summary>
        internal static string SecurityCouldNotGetSetting {
            get {
                return ResourceManager.GetString("SecurityCouldNotGetSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to access to the key store. Please check permission to READ_PHONE_STATE is granted..
        /// </summary>
        internal static string SecurityPermissions {
            get {
                return ResourceManager.GetString("SecurityPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your profile.
        /// </summary>
        internal static string SelectYourProfileTitle {
            get {
                return ResourceManager.GetString("SelectYourProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPLETED.
        /// </summary>
        internal static string SummaryHeaderCompleted {
            get {
                return ResourceManager.GetString("SummaryHeaderCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IN PROGRESS.
        /// </summary>
        internal static string SummaryHeaderInProgress {
            get {
                return ResourceManager.GetString("SummaryHeaderInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create your first test.
        /// </summary>
        internal static string SummaryMiddleText {
            get {
                return ResourceManager.GetString("SummaryMiddleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW TEST.
        /// </summary>
        internal static string SummaryNewTestButton {
            get {
                return ResourceManager.GetString("SummaryNewTestButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} QUESTIONS LEFT.
        /// </summary>
        internal static string SummaryQuestionsLeft {
            get {
                return ResourceManager.GetString("SummaryQuestionsLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        internal static string SummaryTitle {
            get {
                return ResourceManager.GetString("SummaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mr..
        /// </summary>
        internal static string TitleMr {
            get {
                return ResourceManager.GetString("TitleMr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ms..
        /// </summary>
        internal static string TitleMs {
            get {
                return ResourceManager.GetString("TitleMs", resourceCulture);
            }
        }
    }
}
